### ISSUE TITLE
Cannot get favorite list

### ISSUE THREAD

**Issue by afterdelight** [AlphaSlayer1964/kemono-dl#124]
### Version
 
Version: latest

### Your Command
>kemono-dl.py --cookies kemono_cookies.txt --kemono-fav-users patreon --skip-filetypes psd --post-timeout 10 --archive patreon_downloaded.txt

### Description of bug
Cannot get favorite list

 

### Error messages and tracebacks
``` 
ERROR:Unable to get favorite users from kemono.party
Traceback (most recent call last):
  File "F:\downloader\kemono.party\kemono-dl-main\src\main.py", line 657, in start_download
    self.get_favorites('kemono.party', 'artist', self.k_fav_users)
  File "F:\downloader\kemono.party\kemono-dl-main\src\main.py", line 126, in get_favorites
    self.get_post(f"https://{domain}/{favorite['service']}/user/{favorite['id']}")
  File "F:\downloader\kemono.party\kemono-dl-main\src\main.py", line 162, in get_post
    post = self.clean_post(post, user, site)
  File "F:\downloader\kemono.party\kemono-dl-main\src\main.py", line 326, in clean_post
    content_soup = self.get_inline_images(new_post, content_soup)
  File "F:\downloader\kemono.party\kemono-dl-main\src\main.py", line 231, in get_inline_images
    inline_images = [inline_image for inline_image in content_soup.find_all("img") if inline_image['src'][0] == '/']
  File "F:\downloader\kemono.party\kemono-dl-main\src\main.py", line 231, in <listcomp>
    inline_images = [inline_image for inline_image in content_soup.find_all("img") if inline_image['src'][0] == '/']
  File "C:\Python\Python310\lib\site-packages\bs4\element.py", line 1519, in __getitem__
    return self.attrs[key]
KeyError: 'src'
```

**Comment by CCRcmcpe** [comment]
https://github.com/AlphaSlayer1964/kemono-dl/blob/5bfab2ee925c3dcd092bbe4ad0532fe504b34cc7/src/main.py#L644
Remove `, retry=self.retry` as a workaround.
BTW, the repository owner seems not responsive.
