### ISSUE TITLE
ERROR: Unable to get favorite users from kemono.party

### ISSUE THREAD

**Issue by itsaferbie** [AlphaSlayer1964/kemono-dl#137]
### Version

Version: 2022.04.27

### Your Command

```bash

python kemono-dl.py --cookies "kemono.party_cookies.txt" --dirname-pattern "X:\smol\Kemono\{service}\{username} [{user_id}]" --filename-pattern "[{published}] [{id}] {title}\[{index}]_{filename}.{ext}" --inline-filename-pattern "[{published}] [{id}] {title}\inline\[{index}]_{filename}.{ext}" --kemono-fav-users all

```

### Description of bug

No download begins, throws error for not finding favorite users.

### How To Reproduce

Open command prompt in folder for python script, put in command above.

### Error messages and tracebacks

```python

ERROR:Unable to get favorite users from kemono.party
Traceback (most recent call last):
  File "X:\smol\kemono-dl\src\main.py", line 630, in start_download
    self.get_favorites('kemono.party', 'artist', self.k_fav_users)
  File "X:\smol\kemono-dl\src\main.py", line 126, in get_favorites
    self.get_post(f"https://{domain}/{favorite['service']}/user/{favorite['id']}")
  File "X:\smol\kemono-dl\src\main.py", line 161, in get_post
    post = self.clean_post(post, user, site)
  File "X:\smol\kemono-dl\src\main.py", line 329, in clean_post
    new_post['post_variables']['user_updated'] = datetime.datetime.strptime(user['updated'], r'%a, %d %b %Y %H:%M:%S %Z').strftime(self.date_strf_pattern) if user['updated'] else None
TypeError: strptime() argument 1 must be str, not float

```

### Additional comments

[debug.log](https://github.com/AlphaSlayer1964/kemono-dl/files/9594826/debug.log)

**Comment by afterdelight** [comment]
use this fork
https://github.com/L4cache/kemono-dl/commit/c0dd751be4cba57de0f5168bba8cd905614e08c3

**Comment by itsaferbie** [comment]
I tried their fork earlier, but it gave me an error for --dirname-pattern.

But using this fork worked: [Fork](https://github.com/Cercospora/kemono-dl)

**Comment by afterdelight** [comment]
yeah he updated and merged his fork with the other fork.
i tried it and it worked. here is my fork with both fork combined and added some stuff and utf-8 support to make stuff easier
https://github.com/rum416/kemono-dl
but beware it has different folder structure, different args option and different archive structure.
