### ISSUE TITLE
Unable to get posts

### ISSUE THREAD

**Issue by TheSonic03** [AlphaSlayer1964/kemono-dl#139]
Today i try to download a link of kemono but i receive this error:
```
2022-09-19 21:33:11,759:DEBUG:Getting creator json from https://kemono.party/api/creators/
2022-09-19 21:33:12,210:DEBUG:Requesting user json from: https://kemono.party/api/fanbox/user/2848117?o=0
2022-09-19 21:33:12,256:ERROR:Unable to get posts for https://kemono.party/fanbox/user/2848117
Traceback (most recent call last):
  File "A:\_B_\kemono-dl-2022.04.27\src\main.py", line 641, in start_download
    self.get_post(url)
  File "A:\_B_\kemono-dl-2022.04.27\src\main.py", line 161, in get_post
    post = self.clean_post(post, user, site)
  File "A:\_B_\kemono-dl-2022.04.27\src\main.py", line 329, in clean_post
    new_post['post_variables']['user_updated'] = datetime.datetime.strptime(user['updated'], r'%a, %d %b %Y %H:%M:%S %Z').strftime(self.date_strf_pattern) if user['updated'] else None
TypeError: strptime() argument 1 must be str, not float

```
And this is the command:
`python kemono-dl.py --cookies "cookie.txt" --inline --skip-filetypes "psd,clip" --links https://kemono.party/fanbox/user/2848117 --verbose`

It doesn't matter which link i download i always receive this error.

This is my version of kemono-dl.py: `2022.04.27`.

I tried to update the PIP but nothing as chainged.

Sorry for the bad english im italian.

**Comment by afterdelight** [comment]
try this fork
https://github.com/L4cache/kemono-dl

**Comment by afterdelight** [comment]
`pip uninstall kemono-dl`
then
`pip install https://github.com/L4cache/kemono-dl/archive/refs/heads/main.zip --no-cache-dir`

**Comment by TheSonic03** [comment]
> `pip uninstall kemono-dl` then `pip install https://github.com/L4cache/kemono-dl/archive/refs/heads/main.zip --no-cache-dir`

Sorry but I don't understand what to do. Can you please explain what you need to do

**Comment by afterdelight** [comment]
open cmd on windows then paste the commands?

**Comment by TheSonic03** [comment]
The first command give me this message: `WARNING: Skipping kemono-dl as it is not installed.`

The second: 
```
`Collecting https://github.com/L4cache/kemono-dl/archive/refs/heads/main.zip
  Downloading https://github.com/L4cache/kemono-dl/archive/refs/heads/main.zip
     - 19.8 kB 508.2 kB/s 0:00:00
ERROR: https://github.com/L4cache/kemono-dl/archive/refs/heads/main.zip does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.`
```

**Comment by afterdelight** [comment]
uhh sorry i was sleepy.. what i meant is to download
https://github.com/L4cache/kemono-dl/archive/refs/heads/main.zip 
and then extract to your kemono-dl archive folder then run command kemono-dl like usual.

**Comment by TheSonic03** [comment]
> uhh sorry i was sleepy.. what i meant is to download https://github.com/L4cache/kemono-dl/archive/refs/heads/main.zip with regular downloader then extract the zip and overwrite your old kemono-dl archive folder then run kemono-dl.py like usual.

Thanks now it works!

**Comment by baraa272** [comment]
fork works flawlessly here also

**Comment by elois1uchiha** [comment]
> uhh sorry i was sleepy.. what i meant is to download https://github.com/L4cache/kemono-dl/archive/refs/heads/main.zip with regular downloader then extract the zip and overwrite your old kemono-dl archive folder then run kemono-dl.py like usual.

It works!!! Thanks!
