### ISSUE TITLE
noob here need some help

### ISSUE THREAD

**Issue by momo5120** [AlphaSlayer1964/kemono-dl#147]
when i try to do the cookie.txt i keep getting

C:\Users\mh\AppData\Local\Programs\Python\Python310\python.exe: can't find '__main__' module in 'C:\\Users\\mh\\kemono-dl.py'

any way to fix ty

**Comment by ovear** [comment]
Download full source code and extract to one single folder should help.

**Comment by momo5120** [comment]
> Download full source code and extract to one single folder should help.

C:\Users\mh>py kemono-dl.py --cookies "cookie.txt" --links https://kemono.party/patreon/user/34664186
Traceback (most recent call last):
  File "C:\Users\mh\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mh\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\mh\kemono-dl.py\__main__.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by afterdelight** [comment]
`pip install requests` on cmd

**Comment by momo5120** [comment]
> 

sorry for asking for help so much

**Comment by momo5120** [comment]
C:\Users\mh>py kemono-dl.py --cookies "cookie.txt" --links https://kemono.party/patreon/user/34664186
Traceback (most recent call last):
  File "C:\Users\mh\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mh\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\mh\kemono-dl.py\__main__.py", line 12, in <module>
    from .args import get_args
ImportError: attempted relative import with no known parent package

**Comment by afterdelight** [comment]
cd to kemono-dl folder where requirements.txt is located
then exec
`pip install -r requirements.txt`

**Comment by momo5120** [comment]
ok got it working how do i download video files ty
