### ISSUE TITLE
Error with --archive 

### ISSUE THREAD

**Issue by FGuajardoV** [AlphaSlayer1964/kemono-dl#154]
### Version

Version: 2022.04.28

### Your Command

```bash

python kemono-dl.py --cookies .\cookies.txt --links https://kemono.party/fantia/user/17148 --filename-pattern "[{id}] [{index}] {filename}.{ext}" --archive Archive/nagisa.txt

```

### Description of bug

I tried to download using the command --archive but I get the error described below, Works fine when you didnt add that

### Error messages and tracebacks

```python
Traceback (most recent call last):
  File "E:\***\kemono\kemono-dl.py", line 4, in <module>
    main()
  File "E:\***\kemono\src\main.py", line 729, in main
    downloader(get_args())
  File "E:\***\kemono\src\main.py", line 98, in __init__
    self.start_download()
  File "E:\***\kemono\src\main.py", line 657, in start_download
    self.load_archive()
  File "E:\***\kemono\src\main.py", line 564, in load_archive
    self.archive_list = f.read().splitlines()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 35: character maps to <undefined>

```

### Additional comments

Im using this fork https://github.com/L4cache/kemono-dl

**Comment by ovear** [comment]
Seems some kind of encoding problem, will try to fix it.
