### ISSUE TITLE
ERROR:Unable to get

### ISSUE THREAD

**Issue by posteriorjohnson** [AlphaSlayer1964/kemono-dl#158]
### Version

Version: 2022.04.27

### Your Command

python kemono-dl.py --cookies "cookies.txt" --kemono-fav-users patreon

### Description of bug

Any download command using kemono results in an error. have tried --links as well with same error. coomer works fine.

### Error messages and tracebacks

```

ERROR:Unable to get favorite users from kemono.party
Traceback (most recent call last):
  File "C:\***\kemono-dl-2022.04.27\src\main.py", line 630, in start_download
    self.get_favorites('kemono.party', 'artist', self.k_fav_users)
  File "C:\***\kemono-dl-2022.04.27\src\main.py", line 126, in get_favorites
    self.get_post(f"https://{domain}/{favorite['service']}/user/{favorite['id']}")
  File "C:\***\kemono-dl-2022.04.27\src\main.py", line 161, in get_post
    post = self.clean_post(post, user, site)
  File "C:\***\kemono-dl-2022.04.27\src\main.py", line 329, in clean_post
    new_post['post_variables']['user_updated'] = datetime.datetime.strptime(user['updated'], r'%a, %d %b %Y %H:%M:%S %Z').strftime(self.date_strf_pattern) if user['updated'] else None
TypeError: strptime() argument 1 must be str, not float

**Comment by ovear** [comment]
Try my fork

https://github.com/ovear/kemono-dl/

**Comment by posteriorjohnson** [comment]
> Try my fork to see if work
> 
> https://github.com/ovear/kemono-dl/

Works good, thanks!
