### ISSUE TITLE
Can't download anything with latest release.

### ISSUE THREAD

**Issue by TechnoMasterBoy** [AlphaSlayer1964/kemono-dl#162]
### Version

Version: Latest as of now (kemono-dl 2022.04.27)

### Your Command

python kemono-dl.py --cookies "kemono.party_cookies.txt" --verbose --links https://kemono.party/patreon/user/5564244

### Description of bug
I hadn't used this in quite a while. I had the kemono-dl-2022.02.21 version, but it all of a sudden stopped working. Something about failing to import yt-dlp or something. So I decided to update to latest version 2022.04.27, but now I'm getting error below, on anything I try to download. I've tried both Patreon and Pixiv Fanbox.
coomer.party however works fine. It's just kemono.party not working.
I've tried replacing python in the command with python3 aswell as py, but no luck. Always the same error, even with different creators.

### How To Reproduce
Follow exact instructions on how to download and use command above.

### Error messages and tracebacks

DEBUG:Getting creator json from https://kemono.party/api/creators/
DEBUG:Requesting user json from: https://kemono.party/api/patreon/user/5564244?o=0
ERROR:Unable to get posts for https://kemono.party/patreon/user/5564244
Traceback (most recent call last):
  File "C:\Users\Anon\Downloads\kemono-dl-2022.04.27\src\main.py", line 641, in start_download
    self.get_post(url)
  File "C:\Users\Anon\Downloads\kemono-dl-2022.04.27\src\main.py", line 161, in get_post
    post = self.clean_post(post, user, site)
  File "C:\Users\Anon\Downloads\kemono-dl-2022.04.27\src\main.py", line 329, in clean_post
    new_post['post_variables']['user_updated'] = datetime.datetime.strptime(user['updated'], r'%a, %d %b %Y %H:%M:%S %Z').strftime(self.date_strf_pattern) if user['updated'] else None
TypeError: strptime() argument 1 must be str, not float

### Additional comments
I have Python 3.10, and seeing how old the latest version of kemono.dl, maybe that's causing an issue?
Edited out my name of debug log for privacy reasons only.

[debug.log](https://github.com/AlphaSlayer1964/kemono-dl/files/9957855/debug.log)

**Comment by ovear** [comment]
Try my fork instead to see if it work.

https://github.com/ovear/kemono-dl

**Comment by TechnoMasterBoy** [comment]
> Try my fork instead to see if it work.
> 
> https://github.com/ovear/kemono-dl

That works for some reason.

**Comment by hanabiflower6** [comment]
> Try my fork instead to see if it work.
> 
> https://github.com/ovear/kemono-dl

wow thanks this actually works

**Comment by medy17** [comment]
Thanks. It worked.
