### ISSUE TITLE
RuntimeWarning: Pillow 9.1.0 does not support Python 3.11 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.   

### ISSUE THREAD

**Issue by bropsycho** [AlphaSlayer1964/kemono-dl#164]
/*

the main error is:  
 RuntimeWarning: Pillow 9.1.0 does not support Python 3.11 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
        lambda: warnings.warn(*/

PS D:\exclusive\kemono-dl-main\kemono-dl-main> python kemono-dl.py --cookies "cookie.txt" --links https://kemono.party/patreon/user/742938
Traceback (most recent call last):
  File "D:\exclusive\kemono-dl-main\kemono-dl-main\kemono-dl.py", line 1, in <module>
    from src.main import main
  File "D:\exclusive\kemono-dl-main\kemono-dl-main\src\main.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
PS D:\exclusive\kemono-dl-main\kemono-dl-main> py kemono-dl.py --cookies "cookie.txt" --links https://kemono.party/patreon/user/742938
Traceback (most recent call last):
  File "D:\exclusive\kemono-dl-main\kemono-dl-main\kemono-dl.py", line 1, in <module>
    from src.main import main
  File "D:\exclusive\kemono-dl-main\kemono-dl-main\src\main.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
PS D:\exclusive\kemono-dl-main\kemono-dl-main> pip install -r requirements.txt
Collecting beautifulsoup4==4.11.1
  Using cached beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
Collecting Pillow==9.1.0
  Using cached Pillow-9.1.0.tar.gz (49.8 MB)
  Preparing metadata (setup.py) ... done
Collecting requests==2.27.1
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting yt_dlp==2022.4.8
  Using cached yt_dlp-2022.4.8-py2.py3-none-any.whl (2.6 MB)
Requirement already satisfied: soupsieve>1.2 in c:\users\shanto\appdata\local\programs\python\python311\lib\site-packages (from beautifulsoup4==4.11.1->-r requirements.txt (line 1)) (2.3.2.post1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\shanto\appdata\local\programs\python\python311\lib\site-packages (from requests==2.27.1->-r requirements.txt (line 3)) (1.26.13)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.9.24-py3-none-any.whl (161 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting mutagen
  Using cached mutagen-1.46.0-py3-none-any.whl (193 kB)
Requirement already satisfied: pycryptodomex in c:\users\shanto\appdata\local\programs\python\python311\lib\site-packages (from yt_dlp==2022.4.8->-r requirements.txt (line 4)) (3.15.0)
Requirement already satisfied: websockets in c:\users\shanto\appdata\local\programs\python\python311\lib\site-packages (from yt_dlp==2022.4.8->-r requirements.txt (line 4)) (10.4)
Requirement already satisfied: brotli in c:\users\shanto\appdata\local\programs\python\python311\lib\site-packages (from yt_dlp==2022.4.8->-r requirements.txt (line 4)) (1.0.9)
Installing collected packages: Pillow, mutagen, idna, charset-normalizer, certifi, beautifulsoup4, yt_dlp, requests
  Attempting uninstall: Pillow
    Found existing installation: Pillow 9.3.0
    Uninstalling Pillow-9.3.0:
      Successfully uninstalled Pillow-9.3.0
  DEPRECATION: Pillow is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for Pillow ... error
  error: subprocess-exited-with-error

  × Running setup.py install for Pillow did not run successfully.
  │ exit code: 1
  ╰─> [195 lines of output]
      running install
      C:\Users\shanto\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ContainerIO.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ExifTags.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\features.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FitsImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FontFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GdImageFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\Image.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageChops.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageCms.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageColor.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageDraw.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageFilter.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageFont.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageGrab.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageMath.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageMode.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageMorph.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageOps.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImagePalette.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImagePath.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageQt.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageSequence.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageShow.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageStat.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageTk.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageTransform.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageWin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\JpegPresets.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PaletteFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PdfParser.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PSDraw.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PyAccess.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\TarIO.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\TiffTags.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\WalImageFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\_binary.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\_util.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\_version.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\__init__.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\__main__.py -> build\lib.win-amd64-cpython-311\PIL
      running egg_info
      writing src\Pillow.egg-info\PKG-INFO
      writing dependency_links to src\Pillow.egg-info\dependency_links.txt
      writing requirements to src\Pillow.egg-info\requires.txt
      writing top-level names to src\Pillow.egg-info\top_level.txt
      reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no files found matching '*.txt'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
      running build_ext

      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      Traceback (most recent call last):
        File "C:\Users\shanto\AppData\Local\Temp\pip-install-5c1m930n\pillow_4cb836381cee4dc3a068711a98cbebc9\setup.py", line 989, in <module>
          setup(
        File "C:\Users\shanto\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\shanto\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\shanto\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\shanto\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\Users\shanto\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\shanto\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\shanto\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\install.py", line 68, in run
          return orig.install.run(self)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\shanto\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\command\install.py", line 698, in run
          self.run_command('build')
        File "C:\Users\shanto\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\shanto\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\shanto\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\shanto\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Users\shanto\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\shanto\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\shanto\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\shanto\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\shanto\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "C:\Users\shanto\AppData\Local\Temp\pip-install-5c1m930n\pillow_4cb836381cee4dc3a068711a98cbebc9\setup.py", line 804, in build_extensions
          raise RequiredDependencyException(f)
      RequiredDependencyException: zlib

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\shanto\AppData\Local\Temp\pip-install-5c1m930n\pillow_4cb836381cee4dc3a068711a98cbebc9\setup.py", line 1009, in <module>
          raise RequiredDependencyException(msg)
      RequiredDependencyException:

      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      C:\Users\shanto\AppData\Local\Temp\pip-install-5c1m930n\pillow_4cb836381cee4dc3a068711a98cbebc9\setup.py:45: RuntimeWarning: Pillow 9.1.0 does not support Python 3.11 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
        lambda: warnings.warn(
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of Pillow
  Moving to c:\users\shanto\appdata\local\programs\python\python311\lib\site-packages\pil\
   from C:\Users\shanto\AppData\Local\Programs\Python\Python311\Lib\site-packages\~il
  Moving to c:\users\shanto\appdata\local\programs\python\python311\lib\site-packages\pillow-9.3.0.dist-info\
   from C:\Users\shanto\AppData\Local\Programs\Python\Python311\Lib\site-packages\~illow-9.3.0.dist-info
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> Pillow

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
PS D:\exclusive\kemono-dl-main\kemono-dl-main>

**Comment by xBranye** [comment]
python3 -m pip install --upgrade Pillow or pip install --upgrade Pillow

pillow 9.3 is the only version that supports Python 3.11 as of this comment

more info here https://pillow.readthedocs.io/en/latest/installation.html#warnings
