### ISSUE TITLE
Newbie Problem - ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by firmanjawa** [AlphaSlayer1964/kemono-dl#166]
Excuse me, as I new. I already install the newest phyton 3.11 and the latest kemono-dl 2022.04.27. I don't know if installed succesfuly but I got like this

note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> Pillow

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

And when I use script python kemono-dl.py --cookies "cookie.txt" --links https://kemono.party/SERVICE/user/USERID

It come out like this

Traceback (most recent call last):
  File "C:\Users\Zafkiel Altrak\Downloads\Compressed\Kemono Downloader\kemono-dl-2022.04.27\kemono-dl.py", line 1, in <module>
    from src.main import main
  File "C:\Users\Zafkiel Altrak\Downloads\Compressed\Kemono Downloader\kemono-dl-2022.04.27\src\main.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by afterdelight** [comment]
`pip install requests`

**Comment by firmanjawa** [comment]
> `pip install requests`

Thans, there sure many  module needed since it new for me.

But there a freking problem again

-------------------------
ERROR:Unable to get list of creators from kemono.party
Traceback (most recent call last):
  File "C:\Users\Zafkiel Altrak\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zafkiel Altrak\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Zafkiel Altrak\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\Zafkiel Altrak\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 467, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "C:\Users\Zafkiel Altrak\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 540, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "C:\Users\Zafkiel Altrak\AppData\Roaming\Python\Python311\site-packages\urllib3\util\ssl_match_hostname.py", line 150, in match_hostname
    raise CertificateError(
urllib3.util.ssl_match_hostname.CertificateError: hostname 'kemono.party' doesn't match either of 'internetpositif.id', 'www.internetpositif.id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zafkiel Altrak\AppData\Roaming\Python\Python311\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Zafkiel Altrak\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Zafkiel Altrak\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Zafkiel Altrak\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "C:\Users\Zafkiel Altrak\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zafkiel Altrak\AppData\Roaming\Python\Python311\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='kemono.party', port=443): Max retries exceeded with url: /api/creators/ (Caused by SSLError(CertificateError("hostname 'kemono.party' doesn't match either of 'internetpositif.id', 'www.internetpositif.id'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zafkiel Altrak\Downloads\Compressed\Kemono Downloader\kemono-dl-2022.04.27\src\main.py", line 611, in start_download
    self.creators += self.get_creators(domain)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zafkiel Altrak\Downloads\Compressed\Kemono Downloader\kemono-dl-2022.04.27\src\main.py", line 101, in get_creators
    return self.session.get(url=creators_api, cookies=self.cookies, headers=self.headers, timeout=self.timeout).json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zafkiel Altrak\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zafkiel Altrak\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zafkiel Altrak\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zafkiel Altrak\AppData\Roaming\Python\Python311\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='kemono.party', port=443): Max retries exceeded with url: /api/creators/ (Caused by SSLError(CertificateError("hostname 'kemono.party' doesn't match either of 'internetpositif.id', 'www.internetpositif.id'")))
ERROR:No creator information was retrieved. | exiting
------------------------------------------------------------
What is that, mmm, do this software can't download r-18 or it have protector to prevent me from download. Plz give me hope xD

**Comment by ovear** [comment]
Seems your network blocked kemono, try vpn instead.
> hostname 'kemono.party' doesn't match either of 'internetpositif.id', 'www.internetpositif.id'

**Comment by afterdelight** [comment]
yeah its blocked by indonesia ISP, try dns changer or vpn
