### ISSUE TITLE
I got bug in line #329

### ISSUE THREAD

**Issue by flsfps** [AlphaSlayer1964/kemono-dl#168]
ERROR:Unable to get posts for https://kemono.party/fanbox/user/60588249
Traceback (most recent call last):
  File "D:\kemono2\src\main.py", line 641, in start_download
    self.get_post(url)
  File "D:\kemono2\src\main.py", line 161, in get_post
    post = self.clean_post(post, user, site)
  File "D:\kemono2\src\main.py", line 329, in clean_post
    new_post['post_variables']['user_updated'] = datetime.datetime.strptime(user['updated'], r'%a, %d %b %Y %H:%M:%S %Z').strftime(self.date_strf_pattern) if user['updated'] else None
TypeError: strptime() argument 1 must be str, not float

This is all the message i got. What am I supposed to do?

**Comment by afterdelight** [comment]
use this fork
https://github.com/L4cache/kemono-dl

**Comment by IIJlOXOCIIAJl** [comment]
> use this fork https://github.com/L4cache/kemono-dl

Thanks, this actually solved the problem. Why is the other version not working

**Comment by afterdelight** [comment]
its an outdated version
