### ISSUE TITLE
Duplicate Files

### ISSUE THREAD

**Issue by PerseusRex** [AlphaSlayer1964/kemono-dl#171]
When running the program for some creators it's downloading the same files again. I'm assuming hashes(?) have changed for those files because the names have changed, but is there a way to ignore files that have been already downloaded?

**Comment by PerseusRex** [comment]
> `--archive` should be a option.

I just want to make sure, the usual line i use is "python kemono-dl.py --cookies "kemono.party_cookies.txt" --from-file "user.txt" --extract-links" do I just add  --archive to something like this "python kemono-dl.py --cookies "kemono.party_cookies.txt" --from-file "user.txt" --extract-links --archive "user.txt""?

**Comment by ovear** [comment]
Use another file for `--archive` to record what this scripts already downloaded, like `--archive archive_user.txt`

**Comment by L4cache** [comment]
You can still use my fork for when creating archive list tho.
https://github.com/L4cache/kemono-dl#options-added-in-this-fork

**Comment by PerseusRex** [comment]
> You can still use my fork for when creating archive list tho. https://github.com/L4cache/kemono-dl#options-added-in-this-fork

Thank you, but just a little bit of help. I might be doing something wrong. I'm using this line: 
 python kemono-dl.py --cookies "kemono.party_cookies.txt" --from-file "user.txt"--dupe-check

but it keeps giving me this error:
Traceback (most recent call last):
  File "kemono-dl.py", line 1, in <module>
    from src.main import main
  File "L:\Kemono\kemono-dl-2022.04.27\src\main.py", line 15, in <module>
    from .logger import logger
  File "L:\Kemono\kemono-dl-2022.04.27\src\logger.py", line 5, in <module>
    args = get_args()
  File "L:\Kemono\kemono-dl-2022.04.27\src\args.py", line 204, in get_args
    action=argparse.BooleanOptionalAction, default=False,
AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'

**Comment by L4cache** [comment]
> > You can still use my fork for when creating archive list tho. https://github.com/L4cache/kemono-dl#options-added-in-this-fork
> 
> Thank you, but just a little bit of help. I might be doing something wrong. I'm using this line: python kemono-dl.py --cookies "kemono.party_cookies.txt" --from-file "user.txt"--dupe-check
> 
> but it keeps giving me this error: Traceback (most recent call last): File "kemono-dl.py", line 1, in from src.main import main File "L:\Kemono\kemono-dl-2022.04.27\src\main.py", line 15, in from .logger import logger File "L:\Kemono\kemono-dl-2022.04.27\src\logger.py", line 5, in args = get_args() File "L:\Kemono\kemono-dl-2022.04.27\src\args.py", line 204, in get_args action=argparse.BooleanOptionalAction, default=False, AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'

This --[no-]something behavior was introduced in python 3.9, so you need 3.9+ to run it, or you can modify the code...
