### ISSUE TITLE
dateafter command not work

### ISSUE THREAD

**Issue by holdfind** [AlphaSlayer1964/kemono-dl#179]
### Version

Version: kemono-dl 2022.04.27

### Your Command

```
python kemono-dl.py --cookies "kemono.party_cookies.txt" --links https://kemono.party/fantia/user/238688 --dateafter 20221118
```

### Description of bug

When I try the "dateafter" command, it show error.
If I remove "dateafter", it can download the content

### How To Reproduce

No idea.

### Error messages and tracebacks
```
<!-- Please include any error messages or tacebacks. -->
INFO:Downloading posts from kemono.party.party | fantia | 霜月しも | 238688
ERROR:Unable to get posts for https://kemono.party/fantia/user/238688
Traceback (most recent call last):
  File "D:\kemono-dl-main\src\main.py", line 665, in start_download
    self.get_post(url)
  File "D:\kemono-dl-main\src\main.py", line 162, in get_post
    post = self.clean_post(post, user, site)
  File "D:\kemono-dl-main\src\main.py", line 297, in clean_post
    new_post['post_variables']['user_updated'] = datetime.datetime.strptime(user['updated'], r'%a, %d %b %Y %H:%M:%S %Z').strftime(self.date_strf_pattern) if user['updated'] else None
TypeError: strptime() argument 1 must be str, not float
```

### Additional comments

debug.log is empty for this error

**Comment by ovear** [comment]
Hi,
Try my fork should work.

https://github.com/ovear/kemono-dl

**Comment by holdfind** [comment]
> Hi, Try my fork should work.
> 
> https://github.com/ovear/kemono-dl

It work now
Thank very much
