### ISSUE TITLE
i have no programming knowledge and im getting an error

### ISSUE THREAD

**Issue by futagyaru** [AlphaSlayer1964/kemono-dl#185]
here is the error/text in my cmd terminal:

C:\Users\cutel\Downloads\kemono-dl-2022.04.27\kemono-dl-2022.04.27>py kemono-dl.py --cookies "cookie.txt" --links https://kemono.party/patreon/user/364196
ERROR:Unable to get posts for https://kemono.party/patreon/user/364196
Traceback (most recent call last):
  File "C:\Users\cutel\Downloads\kemono-dl-2022.04.27\kemono-dl-2022.04.27\src\main.py", line 641, in start_download
    self.get_post(url)
  File "C:\Users\cutel\Downloads\kemono-dl-2022.04.27\kemono-dl-2022.04.27\src\main.py", line 161, in get_post
    post = self.clean_post(post, user, site)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cutel\Downloads\kemono-dl-2022.04.27\kemono-dl-2022.04.27\src\main.py", line 329, in clean_post
    new_post['post_variables']['user_updated'] = datetime.datetime.strptime(user['updated'], r'%a, %d %b %Y %H:%M:%S %Z').strftime(self.date_strf_pattern) if user['updated'] else None
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not float

**Comment by L4cache** [comment]
Check some forks that address this problem

**Comment by oktaviansyah-ardan** [comment]
did anyone find the branch that works tho?

**Comment by OleksiiKulish** [comment]
Looks like currently JSON from kemono.party does not have `user['updated']`, commenting 329 line in src\main.py helps.

**Comment by emojiluxuri** [comment]
#179 
https://github.com/AlphaSlayer1964/kemono-dl/issues/179#issuecomment-1408494858
