### ISSUE TITLE
How to deal with winerror 10061?

### ISSUE THREAD

**Issue by 469705068** [AlphaSlayer1964/kemono-dl#187]
The error are shown below:

Traceback (most recent call last):
  File "C:\Users\Demon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Demon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\Demon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061]

what should i do?

**Comment by ovear** [comment]
Seems network failure, try to use proxy if your ISP blocked kemono.

**Comment by 469705068** [comment]
> Seems network failure, try to use proxy if your ISP blocked kemono.

I can browse kemono normally use explorer, what settings should i check?

**Comment by ovear** [comment]
If you are using proxy software already, those software will adjust your browser proxy setting automatically, which takes no effect to kemono-dl. You may config proxy manually for kemono-dl.
