### ISSUE TITLE
Yesterday it work normal,but suddenly broken

### ISSUE THREAD

**Issue by qiuqiumaomao** [AlphaSlayer1964/kemono-dl#194]
### Version

Version:kemono-dl-2022.04.27

### Your Command

`` python kemono-dl.py --cookies "cookies.txt" --link https://kemono.party/patreon/user/28464855

```

### Description of bug
<!-- A description of the bug. -->
'''a few days ago,When i normally try to download something this happened,it works well just yesterday,I asked GPT and it said that the server ruturn a 404,I try to get the new cookies but it also didn't work.
'''

### How To Reproduce
<!-- Steps to reproduce the bug. -->
1.Copy link from the site
2.Use command i always used 

### Error messages and tracebacks
<!-- Please include any error messages or tacebacks. -->
```<!-- A description of the bug. -->
ERROR:Unable to get list of creators from kemono.party
Traceback (most recent call last):
  File "C:\Users\瑞雪千骐\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\瑞雪千骐\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\瑞雪千骐\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\瑞雪千骐\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\kemono-dl\src\main.py", line 669, in start_download
    self.creators += self.get_creators(domain)
    return self.session.get(url=creators_api, cookies=self.cookies, headers=self.headers, timeout=self.timeout).json()
  File "C:\Users\瑞雪千骐\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 917, in json
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!doctype html>

```

### Additional comments

Appreciate your work,by the way it is not work on kemono.su.hope you can fix it :D

**Comment by billy0402** [comment]
It's cause of kemono update its api base url.
So you will get all 404 not found when using the api.

I have forked a version and tried to fixed it.
But it's not perfect now.
And the api now limit with max 50 posts to get.
Maybe you can try it.
https://github.com/billy0402/kemono-dl

**Comment by ILogOutOnTheToilet** [comment]
I also made an update here:
https://github.com/ILogOutOnTheToilet/kemono-dl/tree/update-api
My branch doesn't support the old ".party" top-level domain, so you need to use the new ".su" top-level domain for the URL.

**Comment by gugulumasiro** [comment]
> I also made an update here: https://github.com/ILogOutOnTheToilet/kemono-dl/tree/update-api My branch doesn't support the old ".party" top-level domain, so you need to use the new ".su" top-level domain for the URL.

I tried your script, but when I try to download a post, it will automatically download all the author's posts.

**Comment by ILogOutOnTheToilet** [comment]
> > I also made an update here: https://github.com/ILogOutOnTheToilet/kemono-dl/tree/update-api My branch doesn't support the old ".party" top-level domain, so you need to use the new ".su" top-level domain for the URL.
> 
> I tried your script, but when I try to download a post, it will automatically download all the author's posts.

What command did you use? It worked fine for me when I tried using `--dateafter` and `--datebefore`, but I didn't test every case since there are no tests to begin with.

**Comment by gugulumasiro** [comment]
> > > I also made an update here: https://github.com/ILogOutOnTheToilet/kemono-dl/tree/update-api My branch doesn't support the old ".party" top-level domain, so you need to use the new ".su" top-level domain for the URL.
> > 
> > 
> > I tried your script, but when I try to download a post, it will automatically download all the author's posts.
> 
> What command did you use? It worked fine for me when I tried using `--dateafter` and `--datebefore`, but I didn't test every case since there are no tests to begin with.

In the use of the previous script, I did not use -- date after and -- date before, but it can still download specific posts by using post_id. It seems that after modification, only the user ID can be recognized, regardless of whether you have added a post_id after the link or not.

**Comment by ILogOutOnTheToilet** [comment]
> > > > I also made an update here: https://github.com/ILogOutOnTheToilet/kemono-dl/tree/update-api My branch doesn't support the old ".party" top-level domain, so you need to use the new ".su" top-level domain for the URL.
> > > 
> > > 
> > > I tried your script, but when I try to download a post, it will automatically download all the author's posts.
> > 
> > 
> > What command did you use? It worked fine for me when I tried using `--dateafter` and `--datebefore`, but I didn't test every case since there are no tests to begin with.
> 
> In the use of the previous script, I did not use -- date after and -- date before, but it can still download specific posts by using post_id. It seems that after modification, only the user ID can be recognized, regardless of whether you have added a post_id after the link or not.

I updated the code, it should work now. I don't download single posts, so didn't catch this issue. The issue was that I wrote a regex only for creator URL, not for the post URL.

**Comment by ILogOutOnTheToilet** [comment]
> > > > I also made an update here: https://github.com/ILogOutOnTheToilet/kemono-dl/tree/update-api My branch doesn't support the old ".party" top-level domain, so you need to use the new ".su" top-level domain for the URL.
> > > 
> > > 
> > > I tried your script, but when I try to download a post, it will automatically download all the author's posts.
> > 
> > 
> > What command did you use? It worked fine for me when I tried using `--dateafter` and `--datebefore`, but I didn't test every case since there are no tests to begin with.
> 
> In the use of the previous script, I did not use -- date after and -- date before, but it can still download specific posts by using post_id. It seems that after modification, only the user ID can be recognized, regardless of whether you have added a post_id after the link or not.

It should work now. They changed the way single posts are returned from array to object and I added a regex that only checked for creators and not posts because I don't usually download by posts.

**Comment by gugulumasiro** [comment]
> > > > > I also made an update here: https://github.com/ILogOutOnTheToilet/kemono-dl/tree/update-api My branch doesn't support the old ".party" top-level domain, so you need to use the new ".su" top-level domain for the URL.
> > > > 
> > > > 
> > > > I tried your script, but when I try to download a post, it will automatically download all the author's posts.
> > > 
> > > 
> > > What command did you use? It worked fine for me when I tried using `--dateafter` and `--datebefore`, but I didn't test every case since there are no tests to begin with.
> > 
> > 
> > In the use of the previous script, I did not use -- date after and -- date before, but it can still download specific posts by using post_id. It seems that after modification, only the user ID can be recognized, regardless of whether you have added a post_id after the link or not.
> 
> It should work now. They changed the way single posts are returned from array to object and I accidentally added a regex that only checked for creators and not posts because I don't usually download by posts.

thank you so much, it truly work for me.

**Comment by Dazven** [comment]
Started from scratch and made sure everything is as it should be, but now getting "ERROR:No creator information was retrieved. | exiting" when trying to download with the user ID. Something I'm missing or did something change again?

**Comment by JamiDEV** [comment]
@ILogOutOnTheToilet Thank you for the fix, quick question, how to remove the folder creation for individual items? Thank you

**Comment by L4cache** [comment]
> @ILogOutOnTheToilet Thank you for the fix, quick question, how to remove the folder creation for individual items? Thank you

Not exactly sure what you talking but maybe you need to modify the filename patterns

**Comment by JamiDEV** [comment]
> > @ILogOutOnTheToilet Thank you for the fix, quick question, how to remove the folder creation for individual items? Thank you
> 
> Not exactly sure what you talking but maybe you need to modify the filename patterns

when downloading the creators content, a folder is made for each individual file based on date. You can end up with 2000 folders.

**Comment by GittyGharial** [comment]
> I also made an update here: https://github.com/ILogOutOnTheToilet/kemono-dl/tree/update-api My branch doesn't support the old ".party" top-level domain, so you need to use the new ".su" top-level domain for the URL.

Hi @ILogOutOnTheToilet , thank you for your hard work fixing kemono-dl!  As of today I think it is not working; I used it last week just fine but today I get this error:

Library/Python/3.11/lib/python/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x11645fb50>: Failed to establish a new connection: [Errno 61] Connection refused

And then a MaxRetryError.

I'm using kemono-dl version 2022.04.28, which seems quite old but on your fork https://github.com/ILogOutOnTheToilet/kemono-dl/tree/update-api the link to the latest release https://github.com/AlphaSlayer1964/kemono-dl/releases/ shows 2022.04.27 as the latest, which is confusing

**Comment by L4cache** [comment]
> > I also made an update here: https://github.com/ILogOutOnTheToilet/kemono-dl/tree/update-api My branch doesn't support the old ".party" top-level domain, so you need to use the new ".su" top-level domain for the URL.
> 
> Hi @ILogOutOnTheToilet , thank you for your hard work fixing kemono-dl! As of today I think it is not working; I used it last week just fine but today I get this error:
> 
> Library/Python/3.11/lib/python/site-packages/urllib3/connection.py", line 186, in _new_conn raise NewConnectionError( urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x11645fb50>: Failed to establish a new connection: [Errno 61] Connection refused
> 
> And then a MaxRetryError.
> 
> I'm using kemono-dl version 2022.04.28, which seems quite old but on your fork https://github.com/ILogOutOnTheToilet/kemono-dl/tree/update-api the link to the latest release https://github.com/AlphaSlayer1964/kemono-dl/releases/ shows 2022.04.27 as the latest, which is confusing
> 
> EDIT: To complicate matters, it appears that it is partially working, just much slower than before: It eventually successfully downloads posts, but it wastes a lot of time attempting to download something else too and getting rejected when it attempts to pull those.

The kemono data servers are not the most stable.

**Comment by GittyGharial** [comment]
" The kemono data servers are not the most stable."

Yeah that was probably it!  Today that issue seems to be gone.
