### ISSUE TITLE
Key name error

### ISSUE THREAD

**Issue by afterdelight** [AlphaSlayer1964/kemono-dl#91]
I got this error with new update. pls halp.

F:\downloader\kemono.party\kemono-dl-main>kemono-dl.py --cookies kemono.party_cookies.txt --from-file gumroad_aroma.txt --dirname-pattern "{site}/{service}/{username} [{user_id}]/{title}" --filename-pattern "[{added}] [{id}] [{index}] {name}.{ext}" --extract-links --banner --icon --yt-dlp --archive gumroad_aroma_downloaded.txt
ERROR:Unable to get posts for https://kemono.party/gumroad/user/4487698848613
Traceback (most recent call last):
  File "F:\downloader\kemono.party\kemono-dl-main\src\main.py", line 640, in start_download
    self.get_post(url)
  File "F:\downloader\kemono.party\kemono-dl-main\src\main.py", line 162, in get_post
    post = self.clean_post(post, user, site)
  File "F:\downloader\kemono.party\kemono-dl-main\src\main.py", line 348, in clean_post
    file['file_path'] = compile_file_path(new_post['post_path'], new_post['post_variables'], file['file_variables'], self.filename_template, self.restrict_ascii)
  File "F:\downloader\kemono.party\kemono-dl-main\src\helper.py", line 38, in compile_file_path
    cleaned_file = clean_file_name(file_split[-1].format(**file_variables, **post_variables))
KeyError: 'name'
ERROR:Unable to get posts for https://kemono.party/gumroad/user/1199729197439
Traceback (most recent call last):
  File "F:\downloader\kemono.party\kemono-dl-main\src\main.py", line 640, in start_download
    self.get_post(url)
  File "F:\downloader\kemono.party\kemono-dl-main\src\main.py", line 162, in get_post
    post = self.clean_post(post, user, site)
  File "F:\downloader\kemono.party\kemono-dl-main\src\main.py", line 348, in clean_post
    file['file_path'] = compile_file_path(new_post['post_path'], new_post['post_variables'], file['file_variables'], self.filename_template, self.restrict_ascii)
  File "F:\downloader\kemono.party\kemono-dl-main\src\helper.py", line 38, in compile_file_path
    cleaned_file = clean_file_name(file_split[-1].format(**file_variables, **post_variables))
KeyError: 'name'

**Comment by AlphaSlayer1964** [comment]
Use bug template.
